# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          scope: '@hmcts'
      - run: yarn install
      - run: yarn lint
      - run: yarn run nx build sa-components
      #- run: yarn test -- add proper tests later
      - run: yarn publish ./dist/libs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}


